### ISSUE TITLE
"trying to make directory" message in dir.create2() is displayed even if the directory exists

### ISSUE THREAD

**Issue by Zachary-Kramer** [Burke-Lauenroth-Lab/SoilWat_R_Wrapper#35]
The message "trying to make directory" will occur even when my directory exists.

This is because !file.exists(path) will not work in this context. Instead, !dir.exists(path) should be used. 

For me, this line is on 132 of part 5 of 5 (4th line shown here).

```
dir.create2 <- compiler::cmpfun(function(path, showWarnings = TRUE, recursive = FALSE, mode = "0777", times = 0) {
  dir.create(path, showWarnings, recursive, mode)
  if(times < 24)
    if(!file.exists(path)) {
      print("trying to make directory again"))
      Recall(path, showWarnings, TRUE, mode, (times+1)) #recursively call the function b/c when run on JANUS with MPI it doesn't seem to make the directories everytime... quite aggravating.
    }
  #else if(recursive == TRUE) #this commented out part makes the directory via the system call mkdir
  #	system(paste("mkdir -p", path), ignore.stdout=TRUE, ignore.stderr=FALSE)
  #else
  #	system(paste("mkdir", path), ignore.stdout=TRUE, ignore.stderr=FALSE)
})
```

**Comment by dschlaep** [comment]
The function 'dir.exists' was added in R v3.2.0. This function was written under R v2.15.

"!file.exists(path) will not work in this context" is not true -- it works on reasonable file systems such as those of unix-alikes. See ?dir.exists: "One of the idiosyncrasies of Windows is that directory creation may report success but create a directory with a different name, for example dir.create("G.S.") creates ‘"G.S"’. This is undocumented, and what are the precise circumstances is unknown (and might depend on the version of Windows). Also avoid directory names with a trailing space."
