### ISSUE TITLE
Multiple issues in 'Start of prodin' section of 4of5 

### ISSUE THREAD

**Issue by CaitlinA** [Burke-Lauenroth-Lab/SoilWat_R_Wrapper#36]
I am running a project with a prod.csv input file with values throughout.

Some bugs I have run into:
Line 1777:
`#temp[is.finite(temp) | !use_it] <- 0 # if one is is requested, then put others to 0`
Sets all my site-specific input values to 0. Not what I want.

Line 1795: 
`swRunScenariosData[[1]]@prod@CanopyHeight[5, use_it] <- height.datfile[use_it]`
height.datfile does not exist. I assume you mean 'temp'

Line 1802:
`temp[is.finite(temp)] <- 0`
Why would I want to change my finite numbers (1) to zero? Maybe I am misunderstanding something here. Also, even changing them all to 0,  ‘HydraulicRedistribution_use’ requires logical values.

Lines 1806 -> 1818
update_biomass() function does not work for seemingly multiple reasons:
- `funct_veg <- match.arg(funct_veg)` - this does nothing
- `veg_incl = lapply(vegs_ids, function(x) use[x])`  'veg_ids' is called as 'vegs_ids' within the function.
- `temp[veg_incl[[k]], k] <- prod_input[, veg_ids[[k]][veg_incl[[k]]]]` - this line does not work as the first 'k' in the loop changes temp's data structure so subsequent ks do not work. I changed it to this:
   `temp[, k] <- as.numeric(prod_input[, veg_ids[[k]][veg_incl[[k]]]])` and it works swimmingly.

@dschlaep

**Comment by dschlaep** [comment]
See comments inline:

btw, a reproducible example would help me to provide more thoughtful comments.


> On Oct 17, 2016, at 17:00, CaitlinA <notifications@github.com> wrote:
> 
> I am running a project with a prod.csv input file with values throughout.
> 
> Some bugs I have run into:
> Line 1777:
> #temp[is.finite(temp) | !use_it] <- 0 # if one is is requested, then put others to 0
> Sets all my site-specific input values to 0. Not what I want.
> 
I don’t see how
        temp <- with(i_sw_input_prod, cbind(
          Composition_GrassFraction, Composition_ShrubFraction, Composition_TreeFraction,
          Composition_ForbFraction, Composition_BareGround))
        temp[is.finite(temp) | !use_it] <- 0 # if one is is requested, then put others to 0
				swRunScenariosData[[1]]@prod@Composition <- temp

can set “all my site-specific input values to 0”. It should only set the not-specified composition values to 0. I don’t understand what else you want.

> Line 1795: 
> swRunScenariosData[[1]]@prod@CanopyHeight[5, use_it] <- height.datfile[use_it]
> height.datfile does not exist. I assume you mean 'temp'
> 
Yes, I guess that whoever wrote that meant 
	swRunScenariosData[[1]]@prod@CanopyHeight[5, use_it] <- temp[use_it]
> Line 1802:
> temp[is.finite(temp)] <- 0
> Why would I want to change my finite numbers (1) to zero? Maybe I am misunderstanding something here. Also, even changing them all to 0, ‘HydraulicRedistribution_use’ requires logical values.
> 
I guess that at some time the code looked like
	temp[is.na(temp)] <- 0
and some programmer replaced it to
	temp[is.finite(temp)] <- 0
without considering that it should have also been negated. I agree that lines 1785 and 1794 should be
	temp[!is.finite(temp)] <- 0
line 1777
	temp[!is.finite(temp) | !use_it] <- 0
and line 1802
	temp[!is.finite(temp)] <- FALSE

> Lines 1806 -> 1818
> update_biomass() function does not work for seemingly multiple reasons:
> 
> funct_veg <- match.arg(funct_veg) - this does nothing
Incorrect, see ?match.arg
> veg_incl = lapply(vegs_ids, function(x) use[x]) ‘veg_ids' is called as 'vegs_ids' within the function.
Fixed.
> temp[veg_incl[[k]], k] <- prod_input[, veg_ids[[k]][veg_incl[[k]]]] - this line does not work as the first 'k' in the loop changes temp's data structure so subsequent ks do not work. I changed it to this: temp[, k] <- as.numeric(prod_input[, veg_ids[[k]][veg_incl[[k]]]]) and it works swimmingly.
I added as.numeric(…). Two questions: 
	- Why is prod_input not numeric when this function is called?
	- Why did you remove veg_incl[[k]] from the left hand side? prod_input and temp need not have the same order of rows.
