### ISSUE TITLE
SOILWAT execution consistently crashes RStudio 

### ISSUE THREAD

**Issue by Zachary-Kramer** [Burke-Lauenroth-Lab/SoilWat_R_Wrapper#37]
Neither I nor Caitlin are able to use the wrapper because RStudio will crash when executing SOILWAT. I wish I could provide more information, but RStudio provides nothing useful.

Notes:
- Has started occurring within the last couple weeks of commits
- use_rcpp is set to FALSE
- I am using Windows 10, Caitlin is using Windows 7

![Example](https://cloud.githubusercontent.com/assets/16931318/19456865/6378ac64-9478-11e6-81b4-aa2d2f4c6654.PNG)

I can provide any extra information as needed.

@CaitlinA 
@dschlaep

**Comment by dschlaep** [comment]
Is this SOILWAT or Rsoilwat? I don’t have this problem on any of my computers and I don’t use RStudio. Alexander uses RStudio and as far as I know he doesn’t have an issue with RStudio — ask him about it.

I don’t run Microsoft OS — I help fixing this issue if you can show that this is an issue with our code and provide a reproducible example. Do you get the same problem with any of the test projects?

-Daniel

**Comment by charlieduso** [comment]
Hello all,

I have been trying to debug the issue on Caitlin's Windows computer. The error does not seem to lie in the new Rcpp functions; I've compiled all of the new functions without fault. I believe the error occurs on line 2746 of part4of4 - when Soilwat is called. Rsoilwat will execute until that line and break during the call.

Zach, can you see if the error occurs on yours as well? If this is the case, I can't determine why Soilwat would be crashing as there hasn't been any recent updates. The only thing I can consider is the arguments that might be passed-in when the call is made.

I hope this has been helpful.

**Comment by charlieduso** [comment]
Is there anything in swRunScenariosData that could possible break SW?

**Comment by Zachary-Kramer** [comment]
Interesting, mine crashes slightly before that:

`runData[[sc]] <- try(sw_exec(inputData = swRunScenariosData[[sc]],
											 weatherList = i_sw_weatherList[[scw]],
									echo = FALSE, quiet = FALSE),
								silent = TRUE)`

I'll keep looking into it, am currently setting up test projects for it.

**Comment by dschlaep** [comment]
We suspected for some time now that there are still remaining memory problems with SOILWAT and/or Rsoilwat. The last we fixed was related to specific input data and a segfault was only expressed on some of our computers (compilers/architectures?): see
	Rsoilwat/tests/testthat/test_SegmentationFault_v3.R <https://github.com/Burke-Lauenroth-Lab/Rsoilwat/blob/09a21262e7d8eaffcdcf74d916e66ed595ade8a0/tests/testthat/test_SegmentationFault_v3.R>

This sounds like a similar case. You could share swRunScenariosData, i_sw_weatherList, sc, and scw: and Alexander or I could test whether we also get a segfault.

**Comment by Zachary-Kramer** [comment]
GitHub is having issues with attaching a .zip file, so I sent it via email, and will look into the segmentation fault test.

**Comment by dschlaep** [comment]
Thanks for the data. BTW, you can save multiple R objects to a RData (rda) file; the file format rds (serialized) is for single objects only (see ?save and ?saveRDS).

When I run Rsoilwat with your data, it runs the simulation successfully (see attached screenshot of the Rsoilwat31::sw_exec call, a plot to demonstrate successful output generation, and my sessionInfo()).

This issue may be specific to Microsoft OS? This may or may not be related to the issue “R CMD build: error on win-builder” I posted some time ago on the Rsoilwat repository (https://github.com/Burke-Lauenroth-Lab/Rsoilwat/issues/18).

Or this issue may be more general: see issue “R cmd check: Error: Abort trap in examples of sw_exec" (https://github.com/Burke-Lauenroth-Lab/Rsoilwat/issues/15).

**Comment by dschlaep** [comment]
Alexander attempted to replicate this bug with different setups using the data shared by Zack.
- on macOS:
    - command-line: segfault
    - RStudio: no bug
- on Windows OS:
    - RGUI: no bug
    - RStudio: crash

[My runs: on macOS: no bug when run on command-line or with RGUI]

**Comment by alexreeder** [comment]
Issue is in file SW_R_lib.c
The crash happens in this loop:
for (i = 0; i < Rinterception_columns; i++)
				SET_STRING_ELT(Rinterception_names_y_dy, i + 2, mkChar(Cinterception_names[i]));

when trying to access Cinterception_names[6].

**Comment by dschlaep** [comment]
> Hi Alex,
> It has worked both for me (Windows 7) and Zzach (Windows 10) in RStudio and R with the use_Rcpp flag set to FALSE. If you could merge it into the SOILWAT master that would be great.
> Awesome! Thank you!
> How did you go about diagnosing the problem?
> Thanks again!,
> Caitlin
>
