### ISSUE TITLE
SOILWAT produces extremely low VWCMATRIC@Year values and failed sites when using SSURGO data

### ISSUE THREAD

**Issue by Zachary-Kramer** [Burke-Lauenroth-Lab/SoilWat_R_Wrapper#46]
**Summary:**
I have been testing my SSURGO extraction with SOILWAT and have quite a few sites that are failing. As far as I can tell, the data is complete, but SOILWAT may dislike some of the numbers (such as huge layer widths). I was wondering if you might have any insight on why these sites are failing. The yearly aggregation numbers seem to correlate with whether or not the site failed, but there could be other factors.

(This may have been more appropriate in the SOILWAT repo, but I don't know what is actually causing the issue, and all of my work has been in the wrapper)

**Background:**
* I have 51 sites
* SSURGO has data for 24 of them. STATSGO filled in the other 27.
* 5 out of 24 SSURGO sites succeeded. 27 out of 27 STATSGO sites succeeded. 
* SSURGO will discard layers with empty data, and if the first layer depth is greater than 15cm it will create a dummy layer with a depth of 15, then insert the rest of the layers normally (see SSURGO-Download-Extract.R lines 492-531). Additionally, if gravel content is lacking it is filled with a value of 0.01 (this only occurred on 1 of the sites).

**Observations:**
* Looking at the dump files for the run, I noticed that VWCMATRIC@Year has **very** small numbers, such as 10^-312, or even just 0.
* However, the days and months have completely normal data; it seems something is going wrong in the yearly aggregation.
* Reducing the layer widths in soil.layers caused sites to succeed.
* For instance, a site with L1=8cm, L2=46cm, and L3=152cm failed. Changing L2 to 15cm caused the site to succeed. This removed the extreme values for layers 1 and 2, but layer 3 still had the extreme values.
* Layer width is not the only factor, as two sites had the same widths but one failed and the other did not, but it seems to be the main culprit.

**Data:**
Here is a collection of data that's hopefully enough to come to some conclusions. I could not include all of the dumps because they are large, but it might be useful to know that the following sites failed: 9, 13, 18, 19, 20, 21, 22, 24, 25, 26, 27, 28, 30, 35, 36, 37, 38, 41, 42. This should be reproduceable with the settings file I included along with the input data (though I am using different versions of p3of5 and p4of5 than you, so changes to them could impact the results).
[2 example sites.zip](https://github.com/Burke-Lauenroth-Lab/SoilWat_R_Wrapper/files/598517/2.example.sites.zip)
[1_Data_SWInput.zip](https://github.com/Burke-Lauenroth-Lab/SoilWat_R_Wrapper/files/598514/1_Data_SWInput.zip)
[2_SWSF_p1of5_Settings_v51.zip](https://github.com/Burke-Lauenroth-Lab/SoilWat_R_Wrapper/files/598524/2_SWSF_p1of5_Settings_v51.zip)

Thanks!

**Comment by Zachary-Kramer** [comment]
Additionally, I wrote a quick script to check for extreme yearly values (e.g. less than 10^-10, and the following fields for each site have them:

[1] "last.dump.do_OneSite_13.RData"
[1] "VWCMATRIC"
[1] "ESTABL"

[1] "last.dump.do_OneSite_18.RData"
[1] "VWCMATRIC"

[1] "last.dump.do_OneSite_19.RData"
[1] "VWCMATRIC"
[1] "ESTABL"

[1] "last.dump.do_OneSite_20.RData"
[1] "VWCMATRIC"
[1] "ESTABL"

[1] "last.dump.do_OneSite_21.RData"
[1] "VWCMATRIC"
[1] "ESTABL"

[1] "last.dump.do_OneSite_22.RData"
[1] "VWCMATRIC"
[1] "ESTABL"

[1] "last.dump.do_OneSite_24.RData"
[1] "VWCMATRIC"
[1] "ESTABL"

[1] "last.dump.do_OneSite_25.RData"
[1] "VWCMATRIC"
[1] "ESTABL"

[1] "last.dump.do_OneSite_26.RData"
[1] "VWCMATRIC"
[1] "ESTABL"

[1] "last.dump.do_OneSite_27.RData"
[1] "VWCMATRIC"
[1] "ESTABL"

[1] "last.dump.do_OneSite_28.RData"
[1] "VWCMATRIC"
[1] "ESTABL"

[1] "last.dump.do_OneSite_30.RData"
[1] "VWCMATRIC"

[1] "last.dump.do_OneSite_35.RData"
[1] "VWCMATRIC"
[1] "ESTABL"

[1] "last.dump.do_OneSite_36.RData"
[1] "VWCMATRIC"
[1] "ESTABL"

[1] "last.dump.do_OneSite_37.RData"
[1] "VWCMATRIC"
[1] "ESTABL"

[1] "last.dump.do_OneSite_38.RData"
[1] "VWCMATRIC"
[1] "ESTABL"

[1] "last.dump.do_OneSite_41.RData"
[1] "VWCMATRIC"
[1] "ESTABL"

[1] "last.dump.do_OneSite_42.RData"
[1] "VWCMATRIC"
[1] "ESTABL"

[1] "last.dump.do_OneSite_9.RData"
[1] "VWCMATRIC"

**Comment by Zachary-Kramer** [comment]
Interestingly, it is not only SSURGO sites that fail in the yearly aggregation. All of my sites produced extreme values, including STATSGO. Because of this, I will no longer be directly debugging this issue, and will instead focus on what is causing SSURGO to fail in the first place. I did observe that many of sites had 0's for monthly data, but had valid daily data.

**Comment by Zachary-Kramer** [comment]
Update:

Line 1827 of SW_Output.C in RSOILWAT seems to be causing the issue, as it updates the VWCBULK when it should be updating VWCMATRIC. Since VWCMATRIC@Year is never updated, the output is likely grabbing random values from memory, hence the differentiating output. The yearly output with the updated variable seems to be the average of the monthly data. If that's what to be expected, then this issue can be closed and RSOILWAT updated. Additionally, if this is the solution, then this issue is not the cause of SSURGO's failed sites.

**Comment by dschlaep** [comment]
Great job! Thank you!

I went ahead and fixed it with commit 1a6c3ea69876459806771f0a1c042fd451c19796

Please test whether this fixes this issue with SSURGO failed sites too.

**Comment by Zachary-Kramer** [comment]
The aggregation does not seem related to SSURGO's failed sites. Should this issue be closed, or should it remain open until the other aggregations are fixed (e.g. ESTABL)?

**Comment by dschlaep** [comment]
I agree that this issue is not related to SSURGO code. VWC-matrix is fixed (https://github.com/Burke-Lauenroth-Lab/SOILWAT/commit/1a6c3ea69876459806771f0a1c042fd451c19796), soil temperature is fixed (https://github.com/Burke-Lauenroth-Lab/SOILWAT/commit/1499ea7799ab22421b8ee33be164c0aff0ee25c7 and https://github.com/Burke-Lauenroth-Lab/Rsoilwat/commit/0a58de566671b6d37e86b87c4466e04084f4bc10), and ESTABL is fixed (https://github.com/Burke-Lauenroth-Lab/SOILWAT/commit/13f6ab71d50b66ac791f389b3d2020b44f148d8d). The unit tests of 'test_exec_and_aggregate' should now watch over these.

I am not sure whether you are referring to additional aggregations not mentioned in this thread so far? If not, then please close the issue.
