### ISSUE TITLE
How to re-write a branch's history to match master

### ISSUE THREAD

**Issue by Zachary-Kramer** [Burke-Lauenroth-Lab/SoilWat_R_Wrapper#47]
My SSURGODownloadExtract branch is based off an older version of master, before you re-wrote the history of it. My branch shows that it has ~1600 commits, instead of master's ~900. I merged master into my branch in hopes that it would fix the history, but it's the same.

Should I re-create my branch off of the new master, or is there another method of matching master's history?

Thanks

**Comment by dschlaep** [comment]
Unfortunately, there is now other way than to obtain a fresh clone and re-incorporate your changes (e.g., with a diff-tool).

Sorry! The upside is that we got rid of  250 MB which were superfluous.

-Daniel

**Comment by ryanmurf** [comment]
@Zachary-Kramer yes.
1.) Commit your changes.
2.) git pull --rebase
This will fast forward to master's commit then try to put your changes on top.

With that number of commits you might want to --squash your changes if you are pushing to master.
